### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by ozielsilveira** [ozielsilveira/data-engineering-project#10]
* [x] Desenvolver o dashboard usando Power BI.
* [x] Configurar para consumo dos dados da camada Gold.
* [x] Testar e validar o dashboard.

**Comment by KauaLibrelato** [comment]
Fiz a versão prévia do bi, vou anexar em zip aqui para mostrar ao professor, tem as 4 kpis que foram pensadas, mas não tem as métricas bem definidas. Utilizei uma OBT fake para fazer as medidas e essa prévia
[engDadosBi.zip](https://github.com/user-attachments/files/15918555/engDadosBi.zip)

**Comment by KauaLibrelato** [comment]
Versão 2 com métricas melhores
[engDadosBi.zip](https://github.com/user-attachments/files/15919532/engDadosBi.zip)

**Comment by KauaLibrelato** [comment]
commitei no repositório essa primeira vez, enquanto realizamos a parte da camada gold com a obt

**Comment by KauaLibrelato** [comment]
[engDadosBi.zip](https://github.com/user-attachments/files/16021477/engDadosBi.zip)
bi atualizado
