### ISSUE TITLE
Ingestão de Dados

### ISSUE THREAD

**Issue by ozielsilveira** [ozielsilveira/data-engineering-project#6]
* [x]  Configurar a ferramenta de orquestração (Azure Data Factory).
* [x] Desenvolver os scripts de ingestão.
* [x] Testar a ingestão de dados.

**Comment by JeanNesi** [comment]
A parte da ingestão de dados foi feita utilizando o Azure Synapse. Ele faz a ingestão automaticamente, então não foi preciso fazer um script, apenas conectar o Mongo ao Synapse e salvar no data lake na camada landing-zone.
