### ISSUE TITLE
Criação do Data Lake

### ISSUE THREAD

**Issue by ozielsilveira** [ozielsilveira/data-engineering-project#7]
* [x] Definir as camadas do Data Lake (Landing, Bronze, Silver, Gold).
* [x] Configurar o object storage.
* [x] Configuração inicial do Data Lake

**Comment by luigimilanez** [comment]
# Landing
- Dados brutos armazenados sem alterações.

## Bronze
- Conversão de formato para Delta Lake.
- Adição de metadados se necessário.
- Correção de tipos de dados.

## Silver
- Limpeza de dados (remoção de duplicatas, tratamento de nulos).
- Renomeação de colunas.
- Integração e junção de tabelas relacionais.
- Padronização e consistência de dados.

## Gold
- Agregações e cálculos.
- Filtragem de dados irrelevantes.
- Criação de tabelas específicas para relatórios e dashboards.
- Otimizações para consultas de alto desempenho.

**Comment by luigimilanez** [comment]
Criado diagrama do modelo relacional, script para criação das tabelas em SQL SERVER, docker-composer para instalação do MinIO e script para a criação das configurações e camadas do MinIO. (Pull Request #4)

**Comment by luigimilanez** [comment]
Criado script Terraform para instância dos containers na azure.
