### ISSUE TITLE
Modelo Dimensional e KPIs

### ISSUE THREAD

**Issue by ozielsilveira** [ozielsilveira/data-engineering-project#9]
* [x] Definir o modelo dimensional (fatos e dimensões ou OBT).
* [x] Desenvolver o modelo dimensional na camada Gold.
* [x] Definir 4 KPIs e 2 métricas.

**Comment by lucasborba111** [comment]
[Métricas e KPIs.txt](https://github.com/user-attachments/files/15918586/Metricas.e.KPIs.txt)

**Comment by lucasborba111** [comment]
[Métricas e KPIs.txt](https://github.com/user-attachments/files/15918604/Metricas.e.KPIs.txt)

Referência para estudo:
https://chatgpt.com/share/48d350ca-0dec-478a-8a4c-d0efc77470b3

Foram definidas as KPIs com base nas métricas estabelecidas. Toda KPI é derivada por pelo menos uma métrica.
